[package]
name = "asynAwait"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
reqwest = { version = "^0.12.5", features = ["blocking", "json"] }
tokio = { version = "1.39.2", features = ["full"] }
